# Generic language for docker builds
language: generic

# run commands as superuser
sudo: required

# enable docker
services:
  - docker

# login on docker hub
before_install:
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"

# build this code into a docker image
install:
  - docker build -t $DOCKER_REPO:$TRAVIS_BRANCH .

# run unit tests
script:
  - docker run -it -e TRAVIS_COMMIT=$TRAVIS_COMMIT -e TRAVIS_BRANCH=$TRAVIS_BRANCH -e TRAVIS_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER -e CODECOV_TOKEN=$CODECOV_TOKEN $DOCKER_REPO:$TRAVIS_BRANCH bash .test.sh

# if tests passes, push the docker image
after_success:
  - docker push $DOCKER_REPO:$TRAVIS_BRANCH

# notify slack about it
env:
  global:
    secure: nTyfjKzmJDtuTm7/fdNoJA2Dp58aoyXrQgGbseXa5Lm0LpafsLsZr+6vZ6Y6IugDkpDzHIJpV62wTctMKXtjpgMVGaoOY+AhL8w+dW3iqiU3mvegh6cYHFhpjAOP+y8GXqN407brYH7At0vzfgB+Nhx3a7NqUgWbGRNwaarwW5tZdBduiCOQwRnlvgys8QDhP9HIwTxFd1zB7qoIhCUhCKzywleKW0XTXPGJeBt3k3Dl8uek4XlqJ+vW9i5xGHKz5AXTUSXqcfgQ9gDP+N0FijjxNcNy+WGYOLU9XrSwrKbgsr8dkJxMspbQmCPdcriWU/li91PoorDHWg+a4Z/nirC2V44sI33dCQv+S13ossMClkaVeV8Bq27Y95M5hLi6lNO47E8kziCo60cF2Wi4oFMSDQbyfJw1M8Liy4nmJ0YXEPrVG7woVjDq7uq11V+mrYhBTLkLyLOORTn+oP+6w7Rob9J4RwjLefTC/LD06cydVSl2mqGmCj/UgdQqmY8Oeo/OlshjV+lw7Y3rq+jmjUKTUFOnGmFU1MsINGbDJVY+TW6w9xWm/a6rqmXt00h5qBcMoyvTsJB024CpNrnujfYpvETQzyWhTy/XiuoqjH4BRV6klcPCv4q7vAOtxC2WBcXNpfBpdbeNQn60XOcvDVqfWMih1xrEKlX+0CFYpAI=
